// for development only
export default {
  embeddings: [
    {
      id: 4534,
      page_id: 7960,
      slug: 'reale-nutzung-und-vegetationsbedeckung-2021-umweltatlas',
      heading: 'Reale Nutzung und Vegetationsbedeckung 2021 (Umweltatlas)',
      content:
        '# Reale Nutzung und Vegetationsbedeckung 2021 (Umweltatlas)\n\n*   Titel: Reale Nutzung und Vegetationsbedeckung 2021 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k06\\_02\\_1nutz\\_vegbestand $$$\n*   Typ: WMS $$$\n*   Name: reale-nutzung-und-vegetationsbedeckung-2021-umweltatlas-wms-3e2af381 $$$\n*   Stichworte: Ackerland,Baumschule,Baunutzung,Bautypen,Bebauung,Berlin,Brachfläche,Flächennutzung,Friedhof,Gartenbau,Gemeinbedarf,Geodaten,Gewerbegebiet,Gewässer,Grünfläche,Grünland,Industriegebiet,Karten,Kerngebiet,Kleingarten,Mischgebiet,Park,Promenade,Sport,Stadtplatz,Umweltatlas,Ver- und Entsorgungseinrichtungen,Verkehrsflächen,Wald,Wasser,Wochenendhausgebiet,Wohngebiet,Wohnnutzung,infoMapAccessService,inspireidentifiziert $$$\n*   Anmerkung: Darstellung der realen Nutzung der bebauten Flächen und der Grün- und Freiflächennutzung auf Grundlage der Blockkarte 1:5.000 des Informationssystems Stadt und Umwelt (ISU5). Bei Flächen mit Doppelnutzung wird die Grün- und Freiflächennutzung dargestellt. Sachdatenstand 31.12.2021 $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb?loginkey=showMap\\&mapId=k06\\_02\\_1nutz\\_vegbestand@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n',
      similarity: 0.856718480587006,
    },
    {
      id: 4532,
      page_id: 7958,
      slug: 'reale-nutzung-und-vegetationsbedeckung-2015-umweltatlas',
      heading: 'Reale Nutzung und Vegetationsbedeckung 2015 (Umweltatlas)',
      content:
        '# Reale Nutzung und Vegetationsbedeckung 2015 (Umweltatlas)\n\n*   Titel: Reale Nutzung und Vegetationsbedeckung 2015 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k06\\_02\\_1nutz\\_vegbestand2015 $$$\n*   Typ: WMS $$$\n*   Name: reale-nutzung-und-vegetationsbedeckung-2015-umweltatlas-wms-f73c6e7b $$$\n*   Stichworte: Ackerland,Baumschule,Baunutzung,Bautypen,Bebauung,Berlin,Brachfläche,Flächennutzung,Friedhof,Gartenbau,Gemeinbedarf,Geodaten,Gewerbegebiet,Gewässer,Grünfläche,Grünland,Industriegebiet,Karten,Kerngebiet,Kleingarten,Mischgebiet,Park,Promenade,Sport,Stadtplatz,Umweltatlas,Ver- und Entsorgungseinrichtungen,Verkehrsflächen,Wald,Wasser,Wochenendhausgebiet,Wohngebiet,Wohnnutzung $$$\n*   Anmerkung: Darstellung der realen Nutzung der bebauten Flächen und der Grün- und Freiflächennutzung auf Grundlage der digitalen Teilblockkarte 1:5.000 (ISU5). Bei Flächen mit Doppelnutzung wird die Grün- und Freiflächennutzung dargestellt. Sachdatenstand 31.12.2015 $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb?loginkey=showMap\\&mapId=k06\\_02\\_1nutz\\_vegbestand2015@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n',
      similarity: 0.854988694190979,
    },
    {
      id: 4533,
      page_id: 7959,
      slug: 'reale-nutzung-und-vegetationsbedeckung-2020-umweltatlas',
      heading: 'Reale Nutzung und Vegetationsbedeckung 2020 (Umweltatlas)',
      content:
        '# Reale Nutzung und Vegetationsbedeckung 2020 (Umweltatlas)\n\n*   Titel: Reale Nutzung und Vegetationsbedeckung 2020 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k06\\_02\\_1nutz\\_vegbestand2020 $$$\n*   Typ: WMS $$$\n*   Name: reale-nutzung-und-vegetationsbedeckung-2020-umweltatlas-wms-14f703c3 $$$\n*   Stichworte: Ackerland,Baumschule,Baunutzung,Bautypen,Bebauung,Berlin,Brachfläche,Flächennutzung,Friedhof,Gartenbau,Gemeinbedarf,Geodaten,Gewerbegebiet,Gewässer,Grünfläche,Grünland,Industriegebiet,Karten,Kerngebiet,Kleingarten,Mischgebiet,Park,Promenade,Sport,Stadtplatz,Umweltatlas,Ver- und Entsorgungseinrichtungen,Verkehrsflächen,Wald,Wasser,Wochenendhausgebiet,Wohngebiet,Wohnnutzung,infoMapAccessService,inspireidentifiziert $$$\n*   Anmerkung: Darstellung der realen Nutzung der bebauten Flächen und der Grün- und Freiflächennutzung auf Grundlage der Blockkarte 1:5.000 des Informationssystems Stadt und Umwelt (ISU5). Bei Flächen mit Doppelnutzung wird die Grün- und Freiflächennutzung dargestellt. Sachdatenstand 31.12.2020 $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb?loginkey=showMap\\&mapId=k06\\_02\\_1nutz\\_vegbestand2020@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n',
      similarity: 0.854740142822266,
    },
    {
      id: 4531,
      page_id: 7957,
      slug: 'reale-nutzung-und-vegetationsbedeckung-2010-umweltatlas',
      heading: 'Reale Nutzung und Vegetationsbedeckung 2010 (Umweltatlas)',
      content:
        '# Reale Nutzung und Vegetationsbedeckung 2010 (Umweltatlas)\n\n*   Titel: Reale Nutzung und Vegetationsbedeckung 2010 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k06\\_02\\_1nutz\\_vegbestand2010 $$$\n*   Typ: WMS $$$\n*   Name: reale-nutzung-und-vegetationsbedeckung-2010-umweltatlas-wms-264647de $$$\n*   Stichworte: Ackerland,Baumschule,Baunutzung,Bautypen,Bebauung,Berlin,Brachfläche,Flächennutzung,Friedhof,Gartenbau,Gemeinbedarf,Geodaten,Gewerbegebiet,Gewässer,Grünfläche,Grünland,Industriegebiet,Karten,Kerngebiet,Kleingarten,Mischgebiet,Park,Promenade,Sport,Stadtplatz,Umweltatlas,Ver- und Entsorgungseinrichtungen,Verkehrsflächen,Wald,Wasser,Wochenendhausgebiet,Wohngebiet,Wohnnutzung $$$\n*   Anmerkung: Darstellung der realen Nutzung der bebauten Flächen und der Grün- und Freiflächennutzung auf Grundlage der digitalen Teilblockkarte 1 : 5.000 (ISU5). Bei Flächen mit Doppelnutzung wird die Grün- und Freiflächennutzung dargestellt. Sachdatenstand 31.12.2010 $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb?loginkey=showMap\\&mapId=k06\\_02\\_1nutz\\_vegbestand2010@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n',
      similarity: 0.853543996810913,
    },
    {
      id: 3746,
      page_id: 7172,
      slug: 'flächennutzung-stadtstruktur-2010-und-versiegelung-2011-umweltatlas',
      heading: 'Flächennutzung, Stadtstruktur 2010 und Versiegelung 2011 (Umweltatlas)',
      content:
        '# Flächennutzung, Stadtstruktur 2010 und Versiegelung 2011 (Umweltatlas)\n\n*   Titel: Flächennutzung, Stadtstruktur 2010 und Versiegelung 2011 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wfs/data/senstadt/sach\\_nutz2010\\_nutzsa $$$\n*   Typ: WFS $$$\n*   Name: flachennutzung-stadtstruktur-2010-und-versiegelung-2011-umweltatlas-wfs-6da37d7d $$$\n*   Stichworte: Baualter,Baumschulen,Baunutzung,Baustellen,Baustruktur,Baustrukturtypen,Bebauung,Belagsart,Berlin,Brachflächen,Campingplätze,Freiflächen,Freiraumstruktur,Friedhöfe,Gemeinbedarf,Gewerbegebiete,Grünflächen,Industriegebiete,Kerngebiete,Kleingartenanlagen,Luftbildauswertung,Mischgebiete,Parkanlagen,Satellitenbildauswertung,Sportanlagen,Sportflächen,Stadtstruktur,Umweltatlas,Ver- und Entsorgung,Versiegelung,Wochenendhausgebiete,Wohnflächen,Wohngebiete,Wälder,bebaut versiegelte Fläche,reale Flächennutzung,unbebaut versiegelte Fläche,unbebaute Flächen $$$\n*   Anmerkung: Die Tabelle zeigt die reale Nutzung der bebauten Flächen, den Grün- und Freiflächenbestand und die Stadtstruktur.\n    Raumbezug Block/Teiblockkarte ISU 5 (Informationssystem Stadt und Umwelt) Stand 2010. $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb/index.jsp?loginkey=alphaDataStart\\&alphaDataId=sach\\_nutz2010\\_nutzsa@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n*   Attribute: neubklar,bezklar,baunklar,grzkl,ststrname,typklar,flalle,vg,vg\\_0,probau,provgneu,provgneu\\_0,kl1,kl2,kl3,kl4,summe,geom\\_3068 $$$\n*   Layer Name: fis:sach\\_nutz2010\\_nutzsaType $$$\n*   Attribute Beschreibung: Bezirksnamen (neu) 1-12,Bezirksnamen (alt),Nutzung der bebauten Flächen,Nutzung der unbebauten Flächen,Stadtstrukturtyp,Flächentyp,Flächengröße (FG) \\[m²],Versiegelung \\[% von FG] (Gleisschotter gilt als versiegelt),Versiegelung \\[% von FG] (Gleisschotter gilt als unversiegelt),bebaut versiegelte Flächen (z.B. Gebäude) \\[% von FG],unbebaut versiegelte Flächen (Vuf) (z.B. Wege) \\[% von FG] (Gleisschotter gilt als versiegelt),unbebaut versiegelte Flächen (Vuf) (z.B. Wege) \\[% von FG] (Gleisschotter gilt als unversiegelt),Belagsart 1 (z.B. Beton) \\[% von VuF],Belagsart 2 (z.B. Großpflaster) \\[% von VuF],Belagsart 3 (z.B. Kleinpflaster) \\[% von VuF],Belagsart 4 (z.B. Rasengittersteine) \\[% von VuF],Einwohneranzahl 2010 $$$\n',
      similarity: 0.852322220802307,
    },
    {
      id: 3747,
      page_id: 7173,
      slug: 'flächennutzung-stadtstruktur-2015-und-versiegelung-2016-umweltatlas',
      heading: 'Flächennutzung, Stadtstruktur 2015 und Versiegelung 2016 (Umweltatlas)',
      content:
        '# Flächennutzung, Stadtstruktur 2015 und Versiegelung 2016 (Umweltatlas)\n\n*   Titel: Flächennutzung, Stadtstruktur 2015 und Versiegelung 2016 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wfs/data/senstadt/sach\\_nutz2015\\_nutzsa $$$\n*   Typ: WFS $$$\n*   Name: flachennutzung-stadtstruktur-2015-und-versiegelung-2016-umweltatlas-wfs-ebc59402 $$$\n*   Stichworte: Baualter,Baumschulen,Baunutzung,Baustellen,Baustruktur,Baustrukturtypen,Bebauung,Belagsart,Berlin,Brachflächen,Campingplätze,Freiflächen,Freiraumstruktur,Friedhöfe,Gemeinbedarf,Geodaten,Gewerbegebiete,Grünflächen,Industriegebiete,Kerngebiete,Kleingartenanlagen,Luftbildauswertung,Mischgebiete,Parkanlagen,Satellitenbildauswertung,Sportanlagen,Sportflächen,Stadtstruktur,Umweltatlas,Ver- und Entsorgung,Versiegelung,Wochenendhausgebiete,Wohnflächen,Wohngebiete,Wälder,bebaut versiegelte Fläche,reale Flächennutzung,unbebaut versiegelte Fläche,unbebaute Flächen $$$\n*   Anmerkung: Die Tabelle zeigt die reale Nutzung der bebauten Flächen, den Grün- und Freiflächenbestand, die Stadtstruktur, die Versiegelung und die Belagsarten.\n    Raumbezug Block/Teilblockkarte ISU5 (Informationssystem Stadt und Umwelt) Stand 31.12.2015. $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb?loginkey=alphaDataStart\\&alphaDataId=sach\\_nutz2015\\_nutzsa@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n*   Attribute: bezirk,woz\\_name,grz\\_name,ststrname,typklar,flalle,str\\_flges,vg,vg\\_0,probau,provgneu,provgneu\\_0,kl1,kl2,kl3,kl4,geom $$$\n*   Layer Name: fis:sach\\_nutz2015\\_nutzsaType $$$\n*   Attribute Beschreibung: Bezirk,Nutzung der bebauten Flächen,Grün- und Freiflächennutzung,Stadtstrukturtyp,Flächentyp,Flächengröße \\[m²],Straßenfläche  \\[m²],Versiegelung, Gleisschotter gilt als versiegelt \\[% von Flächengröße],Versiegelung, Gleisschotter gilt als unversiegelt \\[% von Flächengröße],Bebaut versiegelte Fläche \\[% von Flächengröße],Unbebaut versiegelte Fläche, Gleisschotter gilt als versiegelt \\[% von Flächengröße],Unbebaut versiegelte Fläche, Gleisschotter gilt als unversiegelt \\[% von Flächengröße],Belagsart 1 \\[% von unbebaut versiegelter Fläche],Belagsart 2 \\[% von unbebaut versiegelter Fläche],Belagsart 3 \\[% von unbebaut versiegelter Fläche],Belagsart 4  \\[% von unbebaut versiegelter Fläche] $$$\n',
      similarity: 0.850516736507416,
    },
    {
      id: 3748,
      page_id: 7174,
      slug: 'flächennutzung-stadtstruktur-2020-und-versiegelung-2021-umweltatlas',
      heading: 'Flächennutzung, Stadtstruktur 2020 und Versiegelung 2021 (Umweltatlas)',
      content:
        '# Flächennutzung, Stadtstruktur 2020 und Versiegelung 2021 (Umweltatlas)\n\n*   Titel: Flächennutzung, Stadtstruktur 2020 und Versiegelung 2021 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wfs/data/senstadt/sach\\_nutz2020\\_nutzsa $$$\n*   Typ: WFS $$$\n*   Name: flachennutzung-stadtstruktur-2020-und-versiegelung-2021-umweltatlas-wfs-c78fcbd1 $$$\n*   Stichworte: Baualter,Baumschulen,Baunutzung,Baustellen,Baustruktur,Baustrukturtypen,Bebauung,Belagsart,Berlin,Brachflächen,Campingplätze,Freiflächen,Freiraumstruktur,Friedhöfe,Gemeinbedarf,Geodaten,Gewerbegebiete,Grünflächen,Industriegebiete,Kerngebiete,Kleingartenanlagen,Luftbildauswertung,Mischgebiete,Parkanlagen,Satellitenbildauswertung,Sportanlagen,Sportflächen,Stadtstruktur,Umweltatlas,Ver- und Entsorgung,Versiegelung,Wochenendhausgebiete,Wohnflächen,Wohngebiete,Wälder,bebaut versiegelte Fläche,infoFeatureAccessService,inspireidentifiziert,reale Flächennutzung,unbebaut versiegelte Fläche,unbebaute Flächen $$$\n*   Anmerkung: Die Tabelle zeigt die reale Nutzung der bebauten Flächen, den Grün- und Freiflächenbestand und die Stadtstruktur, die Versiegelung und die Belagsarten.\n    Raumbezug ist die Blockkarte 1:5.000 des Informationssystems Stadt und Umwelt (ISU5), Stand 31.12.2020. $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb?loginkey=alphaDataStart\\&alphaDataId=sach\\_nutz2020\\_nutzsa@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n*   Attribute: schl5,bez,bezirk,woz,woz\\_name,grz,grz\\_name,ststrnr,ststrname,typ,typklar,nutz,nutzung,nutz\\_bauvor,nutzung\\_bauvor,flalle,vg\\_2021,probau\\_2021,provgneu\\_2021,vg\\_0\\_2021,provgneu\\_0\\_2021,kl1,kl2,kl3,kl4,geom $$$\n*   Layer Name: fis:sach\\_nutz2020\\_nutzsaType $$$\n*   Attribute Beschreibung: Schlüssel,Bezirk (Code),Bezirk,Nutzung der bebauten Flächen (Code),Nutzung der bebauten Flächen,Grün- und Freiflächennutzung (Code),Grün- und Freiflächennutzung,Stadtstrukturtyp (Code),Stadtstrukturtyp,Flächentyp (Code),Flächentyp,Flächennutzung Grünvorrang (Code),Flächennutzung Grünvorrang,Flächennutzung Bauvorrang (Code),Flächennutzung Bauvorrang,Flächengröße \\[m²],Versiegelungsgrad 2021, Gleisschotter gilt als versiegelt \\[%],Bebaut versiegelte Fläche 2021 \\[% von Flächengröße],Unbebaut versiegelte Fläche 2021, Gleisschotter gilt als versiegelt \\[% von Flächengröße],Versiegelung 2021, Gleisschotter gilt als unversiegelt \\[% von Flächengröße],Unbebaut versiegelte Fläche 2021, Gleisschotter gilt als unversiegelt \\[% von Flächengröße],Belagsklasse 1 (Asphalt, Beton, usw.) \\[% von unbebaut versiegelter Fläche]],Belagsklasse 2 (Kunststein- u. Plattenbeläge usw.) \\[% von unbebaut versiegelter Fläche],Belagsklasse 3 (Klein- und Mosaikpflaster) \\[% von unbebaut versiegelter Fläche],Belagsklasse 4 (Rasengittersteine, wassergebundene Decke) \\[% von unbebaut versiegelter Fläche] $$$\n',
      similarity: 0.849675953388214,
    },
    {
      id: 3752,
      page_id: 7178,
      slug: 'flächennutzung-und-stadtstruktur-2021-umweltatlas',
      heading: 'Flächennutzung und Stadtstruktur 2021 (Umweltatlas)',
      content:
        '# Flächennutzung und Stadtstruktur 2021 (Umweltatlas)\n\n*   Titel: Flächennutzung und Stadtstruktur 2021 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wfs/data/senstadt/sach\\_nutz $$$\n*   Typ: WFS $$$\n*   Name: flachennutzung-und-stadtstruktur-2021-umweltatlas-wfs-6cfc617d $$$\n*   Stichworte: Baualter,Baumschulen,Baunutzung,Baustellen,Baustruktur,Baustrukturtypen,Bebauung,Belagsart,Berlin,Brachflächen,Campingplätze,Freiflächen,Freiraumstruktur,Friedhöfe,Gemeinbedarf,Geodaten,Gewerbegebiete,Grünflächen,Industriegebiete,Kerngebiete,Kleingartenanlagen,Luftbildauswertung,Mischgebiete,Parkanlagen,Satellitenbildauswertung,Sportanlagen,Sportflächen,Stadtstruktur,Umweltatlas,Ver- und Entsorgung,Versiegelung,Wochenendhausgebiete,Wohnflächen,Wohngebiete,Wälder,bebaut versiegelte Fläche,infoFeatureAccessService,inspireidentifiziert,reale Flächennutzung,unbebaut versiegelte Fläche,unbebaute Flächen $$$\n*   Anmerkung: Die Tabelle zeigt die reale Nutzung der bebauten Flächen, den Grün- und Freiflächenbestand und die Stadtstruktur, die Versiegelung und die Belagsarten.\n    Raumbezug ist die Blockkarte 1:5.000 des Informationssystems Stadt und Umwelt (ISU5), Stand 31.12.2021. $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb?loginkey=alphaDataStart\\&alphaDataId=sach\\_nutz@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n*   Attribute: schl5,bez,bezirk,woz,woz\\_name,grz,grz\\_name,ststrnr,ststrname,typ,typklar,nutz,nutzung,nutz\\_bauvor,nutzung\\_bauvor,flalle,geom $$$\n*   Layer Name: fis:sach\\_nutzType $$$\n*   Attribute Beschreibung: Schlüssel,Bezirk (Code),Bezirk,Nutzung der bebauten Flächen (Code),Nutzung der bebauten Flächen,Grün- und Freiflächennutzung (Code),Grün- und Freiflächennutzung,Stadtstrukturtyp (Code),Stadtstrukturtyp,Flächentyp (Code),Flächentyp,Flächennutzung Grünvorrang (Code),Flächennutzung Grünvorrang,Flächennutzung Bauvorrang (Code),Flächennutzung Bauvorrang,Flächengröße \\[m²] $$$\n',
      similarity: 0.848800957202911,
    },
    {
      id: 4528,
      page_id: 7954,
      slug: 'reale-nutzung-der-bebauten-flächen-2015-umweltatlas',
      heading: 'Reale Nutzung der bebauten Flächen 2015 (Umweltatlas)',
      content:
        '# Reale Nutzung der bebauten Flächen 2015 (Umweltatlas)\n\n*   Titel: Reale Nutzung der bebauten Flächen 2015 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wms/senstadt/realnutz2015 $$$\n*   Typ: WMS $$$\n*   Name: reale-nutzung-der-bebauten-flachen-2015-umweltatlas-wms-d349e40c $$$\n*   Stichworte: Baunutzung,Bautypen,Bebauung,Berlin,Flächennutzung,Gemeinbedarf,Geodaten,Gewerbegebiet,Industriegebiet,Karten,Kerngebiet,Kleingarten,Mischgebiet,Umweltatlas,Ver- und Entsorgungseinrichtungen,Verkehrsflächen,Wochenendhausgebiet,Wohngebiet,Wohnnutzung $$$\n*   Anmerkung: Darstellung der realen Flächennutzung der bebauten Flächen Berlins in 10 Kategorien auf Grundlage der digitalen Teilblockkarte 1 : 5.000 (ISU5) des ISU (Informationssystem Stadt und Umwelt), Sachdatenstand 31.12.2015 $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb?loginkey=showMap\\&mapId=realnutz2015@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n',
      similarity: 0.848705291748047,
    },
    {
      id: 4530,
      page_id: 7956,
      slug: 'reale-nutzung-der-bebauten-flächen-2021-umweltatlas',
      heading: 'Reale Nutzung der bebauten Flächen 2021 (Umweltatlas)',
      content:
        '# Reale Nutzung der bebauten Flächen 2021 (Umweltatlas)\n\n*   Titel: Reale Nutzung der bebauten Flächen 2021 (Umweltatlas) $$$\n*   Service URL: https://fbinter.stadt-berlin.de/fb/wms/senstadt/k06\\_01realnutz $$$\n*   Typ: WMS $$$\n*   Name: reale-nutzung-der-bebauten-flachen-2021-umweltatlas-wms-56519833 $$$\n*   Stichworte: Baunutzung,Bautypen,Bebauung,Berlin,Flächennutzung,Gemeinbedarf,Geodaten,Gewerbegebiet,Industriegebiet,Karten,Kerngebiet,Kleingarten,Mischgebiet,Umweltatlas,Ver- und Entsorgungseinrichtungen,Verkehrsflächen,Wochenendhausgebiet,Wohngebiet,Wohnnutzung,infoMapAccessService,inspireidentifiziert $$$\n*   Anmerkung: Darstellung der realen Flächennutzung der bebauten Flächen in 9 Kategorien auf Grundlage der Blockkarte 1 : 5.000 des Informationssystems Stadt und Umwelt (ISU5), Sachdatenstand 31.12.2021 $$$\n*   Fisbroker URL: https://fbinter.stadt-berlin.de/fb?loginkey=showMap\\&mapId=k06\\_01realnutz@senstadt $$$\n*   Autor: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin $$$\n',
      similarity: 0.847986817359924,
    },
  ],
}
